In [4]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import icecave_functions as ice
from random import *

from numpy.core.records import array
from numpy.lib.stride_tricks import _broadcast_to_dispatcher
#import pygame as pg


######################################################################
########################### Set-ups ##################################


width = 6
length = 6

startpoint = np.array([[0, 2], [0, 3]]) # same as (1, 3), (1, 4)
endpoint = np.array([[3, 7], [4, 7]]) # same as (4, 8), (5, 8)

initial_rocks = np.array([[4, 5]]) # same as (5, 6)
odds_of_rocks = 0.1 # 10% odds of rocks


#######################################################################
#######################################################################


# Plot setups
maps = np.zeros((length + 2, width + 2))

## set rocks
maps[:, 0] = 1
maps[:, width + 1] = 1
maps[length + 1, :] = 1
maps[0, :] = 1
    

## randomly set startpoint
startpoint_save = startpoint
startpoint = startpoint[randint(1, startpoint.shape[0]) - 1]

## check if the start / end move is vertical / horizontal
if startpoint[0] == 0 or startpoint[0] == width + 1:
    vertical_s = 1
    horizontal_s = 0    
else:
    vertical_s = 0
    horizontal_s = 1
    
if endpoint[0][0] == 0 or endpoint[0][0] == length + 1:
    vertical_e = 1
    horizontal_e = 0    
else:
    vertical_e = 0
    horizontal_e = 1


## set initial setups
keep = 1

row = startpoint[0]
column = startpoint[1]

horizontal = horizontal_s
vertical = vertical_s

now = startpoint

### path set
path = np.zeros([(length + 2) * (width + 2), 2])
num_path = 0

### rock set
rocks = np.zeros([(length + 2) * (width + 2), 2])
num_rocks = 0
for i in range(0, initial_rocks.shape[0]):
    rocks[i] = initial_rocks[i]
    num_rocks = num_rocks + 1

#######################################################################
#######################################################################

joints = 0
while keep == 1:
    
    #find stuckpoint
    maps = ice.imstuck(maps)

    #update now_latest
    now_latest = now
    
    #decide next tile
    now, maps, horizontal, rock_now, problemo = ice.nextile(now, maps, horizontal)
    
    #update maps, path, rocks
    maps, path, rocks, num_path, num_rocks = ice.writemap(maps, now, path, rocks, rock_now, num_path, num_rocks, horizontal, now_latest)

    #swap
    horizontal, vertical = vertical, horizontal
    
    if joints > 4:
        #check if the path can end
        keep, maps, path, num_path = ice.endcheck(keep, maps, path, num_path, now, endpoint, horizontal, horizontal_e)
    
    joints = joints + 1

#######################################################################
#######################################################################
# redraw maps

maps = ice.imnotstuck(maps)

rocks = rocks[0 : num_rocks, :]
path = path[0 : num_path, :]

path, num_path = ice.redraw(path, num_path)

## set startpoint as 2, endpoint as 3

for i in range(0, initial_rocks.shape[0]):
    maps[initial_rocks[i][0], initial_rocks[i][1]] = 1
    
for i in range(0, startpoint.shape[0]):
    maps[startpoint_save[i][0], startpoint_save[i][1]] = 2
    
for i in range(0, endpoint.shape[0]):
    maps[endpoint[i][0], endpoint[i][1]] = 3
    
#######################################################################
#######################################################################
# plot


print(num_path)
print(path)
print(rocks)
print(now)

 
with np.printoptions(precision=3, suppress=True):
    print(maps)
    
plt.plot(path[:, 0], path[:, 1], 'ro-')
plt.axis([0, length + 1, 0, width + 1])

plt.plot(rocks[:, 0], rocks[:, 1], 'bo')
plt.show()

IndexError: index 8 is out of bounds for axis 0 with size 8

In [3]:
import numpy as np
maps = np.array([[1, 1, 1, 1, 1], [1, 0, 0, 0, 1], [1, 1, 0, 0, 1], [1, 1, 1, 1, 1]])
print(maps)


for i in range(maps.shape[0]):
    for j in range(maps.shape[1]):
        if maps[i, j] != 1:
            if maps[i, j + 1] == 1 and maps[i, j - 1] == 1:
                maps[i, j] = 10
            elif maps[i + 1, j] == 1 and maps[i - 1, j] == 1:
                maps[i, j] = 10
                
print(maps)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 1 0 0 1]
 [1 1 1 1 1]]
[[ 1  1  1  1  1]
 [ 1 10  0  0  1]
 [ 1  1  0  0  1]
 [ 1  1  1  1  1]]


In [ ]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import icecave_functions as ice
from random import *

from numpy.core.records import array
from numpy.lib.stride_tricks import _broadcast_to_dispatcher
#import pygame as pg


######################################################################
########################### Set-ups ##################################


width = 6
length = 6

startpoint = np.array([[0, 2], [0, 3]]) # same as (1, 3), (1, 4)
endpoint = np.array([[3, 7], [4, 7]]) # same as (4, 8), (5, 8)

initial_rocks = np.array([[4, 5]]) # same as (5, 6)
odds_of_rocks = 0.1 # 10% odds of rocks


#######################################################################
#######################################################################


# Plot setups
maps = np.zeros((length + 2, width + 2))

## set rocks
maps[:, 0] = 1
maps[:, width + 1] = 1
maps[length + 1, :] = 1
maps[0, :] = 1
    

## randomly set startpoint
startpoint_save = startpoint
startpoint = startpoint[randint(1, startpoint.shape[0]) - 1]

## check if the start / end move is vertical / horizontal
if startpoint[0] == 0 or startpoint[0] == width + 1:
    vertical_s = 1
    horizontal_s = 0    
else:
    vertical_s = 0
    horizontal_s = 1
    
if endpoint[0][0] == 0 or endpoint[0][0] == length + 1:
    vertical_e = 1
    horizontal_e = 0    
else:
    vertical_e = 0
    horizontal_e = 1


## set initial setups
keep = 1

row = startpoint[0]
column = startpoint[1]

horizontal = horizontal_s
vertical = vertical_s

now = startpoint

### path set
path = np.zeros([(length + 2) * (width + 2), 2])
num_path = 0

### rock set
rocks = np.zeros([(length + 2) * (width + 2), 2])
num_rocks = 0
for i in range(0, initial_rocks.shape[0]):
    rocks[i] = initial_rocks[i]
    num_rocks = num_rocks + 1

#######################################################################
#######################################################################

while keep == 1:
    
    #find stuckpoint
    maps = ice.imstuck(maps)

    #update now_latest
    now_latest = now
    
    #decide next tile
    now, maps, horizontal, rock_now = ice.nextile(now, maps, horizontal)
    
    #update maps, path, rocks
    maps, path, rocks, num_path, num_rocks = ice.writemap(maps, now, path, rocks, rock_now, num_path, num_rocks, horizontal, now_latest)

    #swap
    horizontal, vertical = vertical, horizontal

    #check if the path can end
    keep, maps, path = ice.endcheck(keep, maps, path, now, endpoint, horizontal, horizontal_e)
    


maps = ice.imnotstuck(maps)

rocks = rocks[0 : num_rocks, :]
path = path[0 : num_path, :]

path, num_path = ice.redraw(path, num_path)

#######################################################################
#######################################################################
# redraw maps

## set startpoint as 2, endpoint as 3

for i in range(0, initial_rocks.shape[0]):
    maps[initial_rocks[i][0], initial_rocks[i][1]] = 1
    
for i in range(0, startpoint.shape[0]):
    maps[startpoint_save[i][0], startpoint_save[i][1]] = 2
    
for i in range(0, endpoint.shape[0]):
    maps[endpoint[i][0], endpoint[i][1]] = 3
    
#######################################################################
#######################################################################
# plot


print(num_path)
print(path)
print(rocks)
print(now)

 
with np.printoptions(precision=3, suppress=True):
    print(maps)
    
plt.plot(path[:, 0], path[:, 1], 'ro-')
plt.axis([0, length + 1, 0, width + 1])

plt.plot(rocks[:, 0], rocks[:, 1], 'bo')
plt.show()

In [9]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import icecave_functions as ice
from random import *

from numpy.core.records import array
from numpy.lib.stride_tricks import _broadcast_to_dispatcher
#import pygame as pg


######################################################################
########################### Set-ups ##################################


width = 6
length = 6

startpoint = np.array([[0, 2], [0, 3]]) # same as (1, 3), (1, 4)
endpoint = np.array([[3, 7], [4, 7]]) # same as (4, 8), (5, 8)

initial_rocks = np.array([[4, 5]]) # same as (5, 6)
odds_of_rocks = 0.1 # 10% odds of rocks


#######################################################################
#######################################################################


## randomly set startpoint
startpoint_save = startpoint
startpoint = startpoint[randint(1, startpoint.shape[0]) - 1]

## check if the start / end move is vertical / horizontal
if startpoint[0] == 0 or startpoint[0] == width + 1:
    vertical_s = 1
    horizontal_s = 0    
else:
    vertical_s = 0
    horizontal_s = 1
    
if endpoint[0][0] == 0 or endpoint[0][0] == length + 1:
    vertical_e = 1
    horizontal_e = 0    
else:
    vertical_e = 0
    horizontal_e = 1


#######################################################################
#######################################################################
### restart point ###

problemo = 1 
while problemo == 1:

    problemo = 0
    
    # Plot setups
    maps = np.zeros((length + 2, width + 2))

    ## set rocks
    maps[:, 0] = 1
    maps[:, width + 1] = 1
    maps[length + 1, :] = 1
    maps[0, :] = 1

    ## set initial setups
    keep = 1

    row = startpoint[0]
    column = startpoint[1]

    horizontal = horizontal_s
    vertical = vertical_s

    now = startpoint

    ### path set
    path = np.zeros([(length + 2) * (width + 2), 2])
    num_path = 0

    ### rock set
    rocks = np.zeros([(length + 2) * (width + 2), 2])
    num_rocks = 0
    for i in range(0, initial_rocks.shape[0]):
        rocks[i] = initial_rocks[i]
        num_rocks = num_rocks + 1

    #######################################################################
    #######################################################################

    joints = 0
    while keep == 1:
        
        #find stuckpoint
        maps = ice.imstuck(maps)

        #update now_latest
        now_latest = now
        
        #decide next tile
        now, maps, horizontal, rock_now = ice.nextile(now, maps, horizontal)
        
        #update maps, path, rocks
        maps, path, rocks, num_path, num_rocks = ice.writemap(maps, now, path, rocks, rock_now, num_path, num_rocks, horizontal, now_latest)

        #swap
        horizontal, vertical = vertical, horizontal
        
        if joints > 4:
            #check if the path can end
            keep, maps, path = ice.endcheck(keep, maps, path, now, endpoint, horizontal, horizontal_e)
        
        joints = joints + 1

#######################################################################
#######################################################################
# redraw maps

maps = ice.imnotstuck(maps)

rocks = rocks[0 : num_rocks, :]
path = path[0 : num_path, :]

path, num_path = ice.redraw(path, num_path)

## set startpoint as 2, endpoint as 3

for i in range(0, initial_rocks.shape[0]):
    maps[initial_rocks[i][0], initial_rocks[i][1]] = 1
    
for i in range(0, startpoint.shape[0]):
    maps[startpoint_save[i][0], startpoint_save[i][1]] = 2
    
for i in range(0, endpoint.shape[0]):
    maps[endpoint[i][0], endpoint[i][1]] = 3
    
#######################################################################
#######################################################################
# plot


print(num_path)
print(path)
print(rocks)
print(now)

 
with np.printoptions(precision=3, suppress=True):
    print(maps)
    
plt.plot(path[:, 0], path[:, 1], 'ro-')
plt.axis([0, length + 1, 0, width + 1])

plt.plot(rocks[:, 0], rocks[:, 1], 'bo')
plt.show()

KeyboardInterrupt: 

In [12]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import icecave_functions as ice
from random import *

from numpy.core.records import array
from numpy.lib.stride_tricks import _broadcast_to_dispatcher
#import pygame as pg


######################################################################
########################### Set-ups ##################################


width = 6
length = 6

startpoint = np.array([[0, 2], [0, 3]]) # same as (1, 3), (1, 4)
endpoint = np.array([[3, 7], [4, 7]]) # same as (4, 8), (5, 8)

initial_rocks = np.array([[4, 5]]) # same as (5, 6)
odds_of_rocks = 0.1 # 10% odds of rocks


#######################################################################
#######################################################################


## randomly set startpoint
startpoint_save = startpoint
startpoint = startpoint[randint(1, startpoint.shape[0]) - 1]

## check if the start / end move is vertical / horizontal
if startpoint[0] == 0 or startpoint[0] == width + 1:
    vertical_s = 1
    horizontal_s = 0    
else:
    vertical_s = 0
    horizontal_s = 1
    
if endpoint[0][0] == 0 or endpoint[0][0] == length + 1:
    vertical_e = 1
    horizontal_e = 0    
else:
    vertical_e = 0
    horizontal_e = 1


#######################################################################
#######################################################################
### restart point ###



problemo = 0

# Plot setups
maps = np.zeros((length + 2, width + 2))

## set rocks
maps[:, 0] = 1
maps[:, width + 1] = 1
maps[length + 1, :] = 1
maps[0, :] = 1

## set initial setups
keep = 1

row = startpoint[0]
column = startpoint[1]

horizontal = horizontal_s
vertical = vertical_s

now = startpoint

### path set
path = np.zeros([(length + 2) * (width + 2), 2])
num_path = 0

### rock set
rocks = np.zeros([(length + 2) * (width + 2), 2])
num_rocks = 0
for i in range(0, initial_rocks.shape[0]):
    rocks[i] = initial_rocks[i]
    num_rocks = num_rocks + 1

    #######################################################################
    #######################################################################
    
horizontal = 1

now = [4, 4]
now_row = now[0]
now_column = now[1]
maps[4, :] = [1, 1, 0, 0, 0, 0.001, 0.001, 1]

print('now')
print(now)

print('initial maps')
print(maps)

map_now = maps[now_row, :]
owns = np.arange(map_now.shape[0])
map_checker = np.zeros(map_now.shape[0])

for i in range(0, map_checker.shape[0]):
    map_checker[i] = 100 * map_now[i] * (now_column - owns[i])
    if map_checker[i] > 99:
        map_checker[i] = 100
    elif map_checker[i] < -99:
        map_checker[i] = -100
print('before rewriting path')
print(map_checker)

for i in range(0, map_checker.shape[0]):  
    if map_checker[i] < 10:
        if map_checker[i] > -10:
            #map_checker[i] = 0
            if (map_checker[i] > 0 and map_checker[i] < 1):
                if i < map_checker.shape[0]:
                    map_checker[i + 1] = 1

            elif (map_checker[i] < 0 and map_checker[i] > -1):
                if i > 0:
                    map_checker[i - 1] = 1
                    
                
print('after re-writing')
print(map_checker)

rockend_1 = 0
rockend_2 = 0
for i in range(0, map_checker.shape[0]):
    if map_checker[i] > 99:
        rockend_1 = i
    if map_checker[i] > -99:
        rockend_2 = i + 1

rockend = np.array([rockend_1, rockend_2])
print('rockend')
print(rockend)

map_checker[now_column] = 1

print('final map_checker')
print(map_checker)

nextile_column = now_column
keep_check = 1

if rockend_1 + 1 == rockend_2 - 1:
    nextile_column = now[1]
    problemo = 1

elif rockend_1 + 1 != rockend_2 - 1:
    problemo = 0
    while keep_check == 1:
        nextile_column = randint(rockend_1 + 1, rockend_2 - 1)
        if map_checker[nextile_column] != 1:
            keep_check = 0

print('problemo')
print(problemo)

now = [now_row, nextile_column]



maps[now[0], now[1]] = 0.001

print('now')
print(now)
print('nextile_column + 1')
print(nextile_column + 1)
print('maps.shape')
print(maps.shape)
print('maps')
print(maps)
# add rock
# is nextile left or right
if nextile_column - now_column < 0:
    maps[now_row, nextile_column - 1] = 1
    rock_now = np.array([now_row, nextile_column - 1])
elif nextile_column - now_column > 0:
    maps[now_row, nextile_column + 1] = 1
    rock_now =np.array([now_row, nextile_column + 1])

print()

now
[4, 4]
initial maps
[[1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    1.    0.    0.    0.    0.001 0.001 1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.   ]]
before rewriting path
[ 100.   100.     0.     0.     0.    -0.1   -0.2 -100. ]
after re-writing
[ 100.   100.     0.     0.     1.     1.    -0.2 -100. ]
rockend
[1 7]
final map_checker
[ 100.   100.     0.     0.     1.     1.    -0.2 -100. ]
problemo
0
now
[4, 3]
nextile_column + 1
4
maps.shape
(8, 8)
maps
[[1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    0.    0.    0.    0.    0.    0.    1.   ]
 [1.    1.    0.    0.001 0.    0.001 0.001 1.   ]
 

In [15]:
a = 1; b = 0
a, b = b, a
print(a)
print(b)

0
1
