In [79]:
# Libraries
import numpy as np
import matplotlib.pyplot as plt
import random
# import pygame as pg

In [80]:
##################################################
# Set-ups

width = 6
length = 6

startpoint = np.array([[0, 2], [0, 3]]) # same as (1, 3), (1, 4)
endpoint = np.array([[3, 7], [4, 7]]) # same as (4, 8), (5, 8)

initial_rocks = np.array([[4, 5]]) # same as (5, 6)
odds_of_rocks = 0.1 # 10% odds of rocks

##################################################

In [81]:
# Plot setups
map = np.zeros((length + 2, width + 2))

## set rocks
map[:, 0] = 1
map[:, width + 1] = 1
map[length + 1, :] = 1
map[0, :] = 1

for i in range(0, initial_rocks.shape[0]):
    map[initial_rocks[i][0], initial_rocks[i][1]] = 1
    
for i in range(0, startpoint.shape[0]):
    map[startpoint[i][0], startpoint[i][1]] = 2
    
for i in range(0, endpoint.shape[0]):
    map[endpoint[i][0], endpoint[i][1]] = 3

print(map)

## randomly set startpoint
startpoint = startpoint[randint(1, startpoint.shape[0]) - 1]

## check if the start / end move is vertical / horizontal
if startpoint[0] == 0:
    vertical_s = 1
    horizontal_s = 0
    
elif startpoint[0] == width + 1:
    vertical_s = 1
    horizontal_s = 0
    
else:
    vertical_s = 0
    horizontal_s = 1
    
if endpoint[0][0] == 0:
    vertical_e = 1
    horizontal_e = 0
    
elif endpoint[0][0] == length + 1:
    vertical_e = 1
    horizontal_e = 0
    
else:
    vertical_e = 0
    horizontal_e = 1

print(horizontal_s)
print(horizontal_e)

## set path array, rocks array, etc.
keep = 1

row = startpoint[0]
column = startpoint[1]

path = np.zeros([2, 2])
path[0] = startpoint
num_path = 2

rocks = np.zeros([initial_rocks.shape[0], 2])

for i in range(1, initial_rocks.shape[0]):
    rocks[i - 1] = initial_rocks[i - 1]

num_rocks = 1

horizontal = horizontal_s
vertical = vertical_s

[[1. 1. 2. 2. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 3.]
 [1. 0. 0. 0. 0. 1. 0. 3.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
0
1


In [62]:
keep = 1

row = startpoint[0]
column = startpoint[1]

path = np.zeros([2, 2])
path[0] = startpoint
num_path = 2;

rocks = np.zeros([initial_rocks.shape[0], 2])

for i in range(1, initial_rocks.shape[0]):
    rocks[i - 1] = initial_rocks[i - 1]

num_rocks = 1;

now = startpoint


0
3
[[0. 3.]
 [0. 0.]]
[[0. 0.]]


In [82]:
# ice-cave puzzle library
def nextile(now):
    now_row = now[0][0]
    now_column = now[0][1]
    
    if horizontal == 1:
        map_now = map[now_row, :]
    else:
        map_now = map[:, now_column]
        
    for i in range(0, map_now.shape[0]):
        

SyntaxError: invalid syntax (<ipython-input-82-3acc495fffed>, line 8)

In [121]:
now = startpoint
horizontal = 0

now_row = now[0]
now_column = now[1]
    
if horizontal == 1:
    map_now = map[now_row, :]
    map_now[now_column] = 999
    owns = np.arange(map_checker.shape[0])
    map_checker = owns - map_now
else:
    map_now = map[:, now_column]
    map_now[now_row] = 999
    owns = np.arange(map_checker.shape[0])
    map_checker = owns - map_now
    
    
for i in range(0, map_checker.shape[0]):
    map_checker[i] = map_checker[i] * map_now[i]
    
    
#check = 
#map_checker = map_now

print(map_now)
print(map_checker)
#for i in range(1, map_now.shape[0]):
    #if map_now[i] == 1
    

[999.   0.   0.   0.   0.   0.   0.   1.]
[-9.98001e+05  0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00
  0.00000e+00  0.00000e+00  6.00000e+00]


In [39]:
# Main code
while keep == 1:
    ## randomly decide the tile from the very-next-path
    ### watch 'the very-next-path', check rocks and early paths, than decide
    ### after deciding the tile, place the rock at the back of the tile
    ### rewrite index, path as 100, rock as 1
    ### update the present tile as the tile decided
    ###
    


